{{/*
© 2019 Nokia
Licensed under the BSD 3 Clause license
SPDX-License-Identifier: BSD-3-Clause
*/}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: caas-ingress-certs
  labels:
{{ include "caas-ingress.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "caas-ingress.gen-certs" . ) | indent 2 }}
